 dist: trusty
 language: csharp
 sudo: required
 mono: none 
 dotnet: 1.0.1   
 install:
   - dotnet restore 
 script:
   - dotnet build Redouble.AspNet.Webpack/Redouble.AspNet.Webpack.csproj
   - dotnet test Test/Test.csproj -parallel none
   - dotnet build Calculator/Calculator.csproj