 dist: trusty
 language: CSharp
 sudo: required
 mono:
   - latest 
 install:
   - sudo apt-get install curl libunwind8 gettext
   - curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=809130
   - sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
   - sudo ln -s /opt/dotnet/dotnet /usr/local/bin
   - dotnet restore 
 script:
   - dotnet build Redouble.AspNet.Webpack/project.json 
   - dotnet test Test/project.json -parallel none
   - dotnet build Calculator/project.json