 language: csharp
 matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
    dotnet: 1.0.1
    mono: none
    env: DOTNETCORE=1
 install:
   - dotnet restore 
 script:
   - dotnet build
   - ulimit -n 512
   - dotnet test Test/Test.csproj