 language: csharp
 matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
    dotnet: 2.0.0-preview2-006497
    mono: none
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    dotnet: 2.0.0-preview2-006497
    mono: none
 install:
   - ulimit -n 1024
   - dotnet restore 
 script:
   - ulimit -n 1024
   - dotnet build
   - dotnet test Test/Test.csproj